DEBUG = True
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_DATABASE_URI = r'mysql://root:root@127.0.0.1/aig_prd_form'
SQLALCHEMY_POOL_SIZE = 5
SQLALCHEMY_POOL_TIMEOUT = 120
SQLALCHEMY_POOL_RECYCLE = 280

MAIL_SERVER = 'smtp.office365.com'
MAIL_PORT = 587
MAIL_USERNAME = r'pkaur@aigbusiness.com'
MAIL_PASSWORD = r'#Pawan1#'
MAIL_USE_TLS = True
MAIL_USE_SSL = False
